### ISSUE TITLE
Table thead fixed css

### ISSUE THREAD

**Issue by ivanhoinacki** [emalherbi/bootTable#6]
``` css
.table-style{
  height: 350px;
  margin-bottom: 9px;
}
#table{
  display: flex;
  flex-flow: column;
  height: 100%;
  width: 100%;
}
#table thead{
  flex: 0 0 auto;
  width: calc(100% - 1.5em);
}
#table tbody{
  flex: 1 1 auto;
  display: block;
  overflow-y: auto;
}
#table tbody tr{
  width: 100%;
}
#table thead,
#table tbody tr{
  display: table;
}
#table tr *:nth-child(2),
#table tr *:nth-child(3),
#table tr *:nth-child(4){
  width: 15%;
}
```

``` html
<div class="row">
  <div class="col-md-12">
    <div class="table-responsive table-style">
      <table id="table" class="table table-bordered table-hover table-condensed">
        <thead>
          <tr>
            <th field="COLUMN"><label>COLUMN</label></th>
            <th width='15%' field="COLUMN"><label>COLUMN</label></th>
            <th width='15%' field="COLUMN"><label>COLUMN</label></th>
            <th width='15%' field="COLUMN"><label>COLUMN</label></th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>
```
